name: publish
on:
  push:
    branches:
      - master
    paths-ignore:
      - package.json
      - package-lock.json
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          git push
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
