name: publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: |
          npm patch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push
      - uses: actions/setup-node@v1
        with:
          node-version: "12.18.2"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
